<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 scorpion.glb --transform
Author: gozdemrl (https://sketchfab.com/gozdemrl)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/scorpion-32836c44c370455da53d489d55a508ea
Title: Scorpion
-->

<script>
	import { T } from "@threlte/core";
	import { useCursor, useDraco, useGltf } from "@threlte/extras";
	import { interactivity } from "@threlte/extras";
	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	const dracoLoader = useDraco();
	const gltf = useGltf("/glb/scorpion-transformed.glb", { dracoLoader });

	interactivity();

	const { onPointerEnter, onPointerLeave } = useCursor();
</script>

<T.Group
	bind:ref
	dispose={false}
	{...props}
	onpointerenter={onPointerEnter}
	onpointerleave={onPointerLeave}
>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group
			rotation={[-Math.PI / 2, 0, -Math.PI / 4]}
			scale={[2e-3, 2e-3, 2e-3]}
		>
			<T.Group rotation={[Math.PI / 2, 0, 0]}>
				<T.Group
					position={[0, 37.73, 0]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				>
					<T.Mesh
						geometry={gltf.nodes.defaultMaterial.geometry}
						material={gltf.materials.Feet}
					/>
					<T.Mesh
						geometry={gltf.nodes.defaultMaterial_1.geometry}
						material={gltf.materials.Feet}
					/>
					<T.Mesh
						geometry={gltf.nodes.defaultMaterial_2.geometry}
						material={gltf.materials.Feet}
					/>
				</T.Group>
				<T.Mesh
					geometry={gltf.nodes.defaultMaterial_3.geometry}
					material={gltf.materials.eyes}
					position={[0, 37.73, 0]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					geometry={gltf.nodes.defaultMaterial_4.geometry}
					material={gltf.materials.Kanca}
					position={[0, 37.73, 0]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					geometry={gltf.nodes.defaultMaterial_5.geometry}
					material={gltf.materials.Alt_zirh}
					position={[0, -4.47, 21.9]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					geometry={gltf.nodes.defaultMaterial_6.geometry}
					material={gltf.materials.Kanca}
					position={[0, 37.73, 68.18]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					geometry={gltf.nodes.defaultMaterial_7.geometry}
					material={gltf.materials.Kanca}
					position={[0, 18.78, 51.58]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					geometry={gltf.nodes.defaultMaterial_8.geometry}
					material={gltf.materials.Zirh}
					position={[0, 37.73, 23.54]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					geometry={gltf.nodes.defaultMaterial_9.geometry}
					material={gltf.materials.Kuyruk}
					position={[-0.04, 11.64, 8.99]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
			</T.Group>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
